// Presentation choices for the selected archive. Project facts remain in the case studies.
export const archiveOrder = ['smart-medication-monitor','suv-battery-cooling','sustainable-plane-seat','prosthetic-limb-analysis','pet-cleaning-tool','architecture-design','light-control-lamp','dancing-segway','ai-football-robot','webapp-game','reverse-engineering-shaver','dataset-prediction'];
export const projectIcons: Record<string,string> = Object.fromEntries(archiveOrder.map(slug=>[slug,slug==='webapp-game'?'/images/projects/webapp-game/player.webp':`/images/project-icons/${slug}.${['suv-battery-cooling','sustainable-plane-seat'].includes(slug)?'webp':'svg'}`]));
export type Presentation = {name:string;focus:string;reason:string;action:string;anchor:string;related:[string,string];chapters?:[string,string][]};
export const presentation: Record<string,Presentation> = {
 'smart-medication-monitor':{name:'Smart Medication',focus:'Combine the evidence. Keep its limits visible.',reason:'Weight change estimates what left the platform; a separate visual signal describes the action. The app retains both, so an event can be reviewed in context.',action:'Explore the two sensing channels',anchor:'med-system',related:['ai-football-robot','light-control-lamp']},
 'suv-battery-cooling':{name:'SUV / Thermal Systems',focus:'Resolve the air outside and the heat inside.',reason:'Aerodynamic shaping and battery cooling share a vehicle package. The case study connects exterior flow features to the separate thermal analysis.',action:'Compare CFD with the wind tunnel',anchor:'vehicle-aero-results',related:['sustainable-plane-seat','prosthetic-limb-analysis'],chapters:[['Vehicle form','vehicle-form'],['Wind tunnel','vehicle-test'],['Aerodynamics','vehicle-aero-results'],['Cold plate','vehicle-cooling'],['Thermal results','vehicle-thermal-results']]},
 'sustainable-plane-seat':{name:'Circular Cabin Seat',focus:'Design for the next repair, as well as the next flight.',reason:'A shared base, removable pans and replaceable soft goods make the seat a set of serviceable parts. Mass and circularity estimates guide the concept.',action:'Explore the three seat systems',anchor:'seat-system',related:['reverse-engineering-shaver','pet-cleaning-tool'],chapters:[['The brief','seat-brief'],['Seat system','seat-system'],['Disassembly','seat-repair'],['Assessment','seat-results']]},
 'prosthetic-limb-analysis':{name:'Running Blade / FEA',focus:'Read stiffness and mass together.',reason:'The iterated CFRP model reduces tip displacement and raises the first natural frequency, while the reported mass increases. Compare those effects together.',action:'Compare geometry and material',anchor:'fea-comparison',related:['suv-battery-cooling','sustainable-plane-seat']},
 'pet-cleaning-tool':{name:'PetEase & Dooti',focus:'One research brief. Two distinct design contributions.',reason:'PetEase is my individual cleaning concept. The team selected Dooti for development, where I contributed to CAD, electronics, power analysis, testing and assembly.',action:'See why the team selected Dooti',anchor:'pet-selection',related:['reverse-engineering-shaver','light-control-lamp']},
 'architecture-design':{name:'The Path / 径',focus:'Test a place at the scale of a person.',reason:'Spatial models helped choose the Path; full-size seating trials changed the furniture towards separable modules. Both scales informed the final unbuilt proposal.',action:'Explore the co-design decisions',anchor:'path-prototypes',related:['sustainable-plane-seat','pet-cleaning-tool']},
 'light-control-lamp':{name:'ShyBloom',focus:'Make the mechanism part of the expression.',reason:'A single servo moves the flower through an umbrella-style linkage. Light sensing and central LEDs turn that physical motion into a responsive object.',action:'Inspect the flower mechanism',anchor:'bloom-mechanics',related:['dancing-segway','smart-medication-monitor']},
 'dancing-segway':{name:'Dancing Segway',focus:'Build control one experiment at a time.',reason:'Beat-driven choreography and pitch-based balance are separate experiments in the archive. Together they show the work of connecting sensing, motor response and feedback.',action:'Follow the five development stages',anchor:'segway-development',related:['ai-football-robot','light-control-lamp']},
 'ai-football-robot':{name:'AI Football / Red Team',focus:'Give the robot a role before refining its behaviour.',reason:'Our red team committed to defence: find the goal and cover the opening. Match footage makes the consequences of visibility, motor direction and positioning tangible.',action:'Watch the red-team match',anchor:'football-film',related:['dancing-segway','smart-medication-monitor']},
 'webapp-game':{name:'Wulin / Webapp Game',focus:'',reason:'',action:'',anchor:'',related:['dancing-segway','dataset-prediction']},
 'reverse-engineering-shaver':{name:'Braun M60 / Teardown',focus:'Understand what carries the impact before redesigning it.',reason:'The teardown connects individual parts to manufacturing and lifecycle estimates. Material and transport energy make the redesign priorities more specific.',action:'Read the lifecycle breakdown',anchor:'lifecycle-title',related:['sustainable-plane-seat','pet-cleaning-tool'],chapters:[['Teardown','anatomy-title'],['Manufacturing','ledger-title'],['Lifecycle','lifecycle-title'],['Redesign','redesign-title']]},
 'dataset-prediction':{name:'Forest CoverType',focus:'A headline score is only the start of the explanation.',reason:'Balancing the classes makes the evaluation easier to read. The confusion matrix then reveals where similar cover types still overlap.',action:'Explore the class-level results',anchor:'results-title',related:['smart-medication-monitor','webapp-game'],chapters:[['Preparation','prep-title'],['Features','explore-title'],['Model','model-title'],['Evaluation','results-title']]}
};
